name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.15
      - uses: actions/checkout@v2.4.0
      - run: make build
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: podsync-${{ matrix.os }}
          path: bin/

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.15
      - uses: actions/checkout@v2.4.0
      - env:
          VIMEO_TEST_API_KEY: ${{ secrets.VIMEO_ACCESS_TOKEN }}
          YOUTUBE_TEST_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: make test

  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/setup-go@v2.2.0
      - uses: actions/checkout@v2.4.0
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.43.0

      - name: Go mod
        env:
          DIFF_PATH: "go.mod go.sum"
        run: |
          go mod tidy
          DIFF=$(git status --porcelain -- $DIFF_PATH)
          if [ "$DIFF" ]; then
            echo
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi
